version: '3.8'

services:
  database:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    deploy:
      resources:
        reservations:
          cpus: '2'
          memory: '2g'
    environment:
      - SA_PASSWORD=YourStrongPassword
      - ACCEPT_EULA=Y
    volumes:
      - sqldata:/var/opt/mssql

  webapp:
    container_name: homies-web
    build:
      context: .
      dockerfile: ./Dockerfile.json
#    image: homies:latest
    ports:
      - "80:80"
    restart: always

volumes:
  sqldata:
    driver: azure_file
    driver_opts:
      share_name: sql-volume
      storage_account_name: homiesstorageacc2